import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark flex flex-col min-h-screen bg-neutral-950 relative">
        <NavBar></NavBar>
        <div className="flex-1">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
